name: devops app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
   
    - name: List Files
      run: |
       echo "Terry is teaching"
  
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install flake8

    - name: Lint Check
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: check out branches
      uses: actions/checkout@v4
    
    - name: Docker logins
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:${{github.sha}} .
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:${{github.sha}}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Yeowon'
        images: '${{ secrets.DOCKER_USERNAME }}/devops-app:${{github.sha}}'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        
        